# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Deep Bio
email: sales@deepbio.co.kr
description: > # this means to ignore newlines until "baseurl:"
  DeepBio - providing deep learning solutions to pathology
baseurl: "" # the subpath of your site, e.g /blog
url: "https://hyooeun.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: deepbio

#Build settings

timezone: Etc/UTC

markdown: kramdown

collections:
  members:
    _hide_content: true
  interns:
    _hide_content: true

paginate: 3
paginate_path: "/event/page:num/"
permalink: pretty

jekyll-archives:
  enabled:
    - categories

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

defaults:
  - scope:
      path: "index.html"
    values:
      layout: "default"
  - scope:
      path: "about.html"
    values:
      layout: "default"
  - scope:
      path: "wwd.html"
    values:
      layout: "default"
